# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 11:24
from __future__ import unicode_literals

from django.db import migrations, models
from unipath import Path

class Migration(migrations.Migration):

    dependencies = [
        ('edc_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadexportreceiptfile',
            name='export_receipt_file',
            field=models.FileField(upload_to=Path('/home/django/uploads'))),
        ),
    ]
