# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models
from unipath import Path


class Migration(migrations.Migration):

    dependencies = [
        ('edc_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadexportreceiptfile',
            name='export_receipt_file',
            field=models.FileField(upload_to=Path('/Users/erikvw/source/tshilo-dikotla/uploads')),
        ),
    ]
