# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('edc_export', '0002_auto_20161124_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporthistory',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='exporthistory',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='exportplan',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='exportplan',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='exportreceipt',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='exportreceipt',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='exporttransaction',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='exporttransaction',
            name='export_uuid',
            field=models.UUIDField(editable=False, help_text='system field for export tracking.', null=True),
        ),
        migrations.AlterField(
            model_name='exporttransaction',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalexporthistory',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalexporthistory',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalexportplan',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalexportplan',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalexportreceipt',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalexportreceipt',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalexporttransaction',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalexporttransaction',
            name='export_uuid',
            field=models.UUIDField(editable=False, help_text='system field for export tracking.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalexporttransaction',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='uploadexportreceiptfile',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='uploadexportreceiptfile',
            name='export_receipt_file',
            field=models.FileField(upload_to='/Users/erikvw/source/edc-export/uploads'),
        ),
        migrations.AlterField(
            model_name='uploadexportreceiptfile',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
    ]
